name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lock-check:
    name: Lockfile consistency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Detect package/lock changes (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        id: changed_pkgs
        uses: tj-actions/changed-files@v45
        with:
          files: |
            package.json
            package-lock.json
            client/package.json
            client/package-lock.json
      - name: Enforce package.json ↔ lockfile pair (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          CHANGED_FILES="${{ steps.changed_pkgs.outputs.all_changed_files }}"
          echo "Changed files:\n$CHANGED_FILES"
          ROOT_PKG_CHANGED=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep -c '^package.json$' || true)
          ROOT_LOCK_CHANGED=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep -c '^package-lock.json$' || true)
          CLIENT_PKG_CHANGED=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep -c '^client/package.json$' || true)
          CLIENT_LOCK_CHANGED=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep -c '^client/package-lock.json$' || true)
          if [ "$ROOT_PKG_CHANGED" -gt 0 ] && [ "$ROOT_LOCK_CHANGED" -eq 0 ]; then
            echo "Root package.json changed without package-lock.json. Run 'npm install --package-lock-only' and commit." >&2
            exit 2
          fi
          if [ "$CLIENT_PKG_CHANGED" -gt 0 ] && [ "$CLIENT_LOCK_CHANGED" -eq 0 ]; then
            echo "client/package.json changed without client/package-lock.json. Run 'cd client && npm install --package-lock-only' and commit." >&2
            exit 2
          fi
          echo "Lockfile pair checks passed."
      - name: npm ci dry-run (root)
        run: npm ci --ignore-scripts --dry-run
      - name: npm ci dry-run (client)
        run: npm ci --ignore-scripts --dry-run
        working-directory: client

  lint:
    name: Lint (root + client)
    needs: lock-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install root deps
        run: npm ci --ignore-scripts
      - name: Lint root (ESLint v8)
        run: npx eslint . --ext .js --max-warnings=0
      - name: Install client deps
        run: npm ci --ignore-scripts
        working-directory: client
      - name: Lint client (ESLint flat config)
        run: npx eslint -c eslint.config.cjs . --max-warnings=0
        working-directory: client
      - name: Get changed UI files (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        id: changed_client
        uses: tj-actions/changed-files@v45
        with:
          files: |
            client/src/**/*.{js,jsx}
      - name: UI rules gate (no-hardcoded-ui)
        if: ${{ github.event_name == 'pull_request' && steps.changed_client.outputs.any_modified == 'true' }}
        working-directory: client
        run: |
          echo "${{ steps.changed_client.outputs.all_changed_files }}" \
            | tr ' ' '\n' \
            | grep -E '^client/src/.*\.(js|jsx)$' \
            | sed 's#^client/##' \
            | xargs -r npx eslint -c eslint.config.cjs --max-warnings=0 --rule "no-hardcoded-ui/no-hardcoded-ui:error"
      - name: UI TS/TSX gate (grep fallback)
        if: ${{ github.event_name == 'pull_request' && steps.changed_client.outputs.any_modified == 'true' }}
        working-directory: client
        shell: bash
        run: |
          CHANGED_TS=$(echo "${{ steps.changed_client.outputs.all_changed_files }}" | tr ' ' '\n' | grep -E '^client/src/.*\.(ts|tsx)$' | sed 's#^client/##' || true)
          if [ -z "$CHANGED_TS" ]; then
            echo "No changed TS/TSX UI files."
            exit 0
          fi
          echo "TS/TSX files to check:" && echo "$CHANGED_TS"
          MATCH_HEX=0
          MATCH_PX=0
          if echo "$CHANGED_TS" | xargs -r grep -nE --color=never '#[0-9A-Fa-f]{3,8}\b' | grep -vE '<svg|<SvgIcon|<[A-Za-z0-9_]+Icon\b' | grep -vE 'var\(|calc\(' ; then
            MATCH_HEX=1
          fi
          if echo "$CHANGED_TS" | xargs -r grep -nE --color=never '(^|[^a-zA-Z-])\d+px\b' | grep -vE '<svg|<SvgIcon|<[A-Za-z0-9_]+Icon\b' | grep -vE 'var\(|calc\(' ; then
            MATCH_PX=1
          fi
          if [ "$MATCH_HEX" -eq 1 ] || [ "$MATCH_PX" -eq 1 ]; then
            echo 'Forbidden hardcoded values found in TS/TSX files:' >&2
            # Re-run to print offending lines clearly
            echo "$CHANGED_TS" | xargs -r grep -nE --color=never '#[0-9A-Fa-f]{3,8}\b|(^|[^a-zA-Z-])\d+px\b' | grep -vE '<svg|<SvgIcon|<[A-Za-z0-9_]+Icon\b' | grep -vE 'var\(|calc\(' >&2 || true
            exit 2
          fi
          echo "TS/TSX check passed: no hardcoded UI values."

  test:
    name: Test (root + client)
    needs: lock-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install root deps
        run: npm ci --ignore-scripts
      - name: Pre-contracts artifacts
        run: npm run precontracts
      - name: Run server tests (Jest)
        env:
          AUTH_DEV_MODE: "1"
          JWT_SECRET: "dev_secret"
        run: npm test -- --ci --runInBand --silent
      - name: Coverage gates (Jest)
        env:
          AUTH_DEV_MODE: "1"
          JWT_SECRET: "dev_secret"
        run: npm run test:cov
      - name: Install client deps
        run: npm ci --ignore-scripts
        working-directory: client
      - name: Run client tests (CRA Jest)
        run: npm test -- --watchAll=false --silent
        working-directory: client

  build:
    name: Build client
    needs: lock-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install client deps
        run: npm ci --ignore-scripts
        working-directory: client
      - name: Build client
        env:
          DISABLE_ESLINT_PLUGIN: "true"
        run: npm run build
        working-directory: client
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/build

  audit:
    name: Security audit (npm)
    needs: lock-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install root deps
        run: npm ci --ignore-scripts
      - name: npm audit (root)
        run: |
          npm audit --audit-level=high || true
      - name: Install client deps
        run: npm ci --ignore-scripts
        working-directory: client
      - name: npm audit (client)
        run: |
          npm audit --audit-level=high || true